/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.PartidasDao;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import model.Jogadores;
import model.Palavras;
import model.Partidas;

/**
 *
 * @author yuki
 */
public class formMenu extends javax.swing.JFrame {

    public static Partidas prtd = new Partidas();
    public static Jogadores jd = new Jogadores();

    public formMenu() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEstatisticas = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnJogar = new javax.swing.JButton();
        btnPalavras = new javax.swing.JButton();
        btnCadastro = new javax.swing.JButton();
        btnTroca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(27, 98, 182));

        btnEstatisticas.setBackground(new java.awt.Color(27, 117, 209));
        btnEstatisticas.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        btnEstatisticas.setForeground(new java.awt.Color(255, 255, 255));
        btnEstatisticas.setText("Estatísticas");
        btnEstatisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstatisticasActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(27, 117, 209));
        btnSair.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jogo da Forca");

        btnJogar.setBackground(new java.awt.Color(27, 117, 209));
        btnJogar.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        btnJogar.setForeground(new java.awt.Color(255, 255, 255));
        btnJogar.setText("Jogar");
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });

        btnPalavras.setBackground(new java.awt.Color(27, 117, 209));
        btnPalavras.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        btnPalavras.setForeground(new java.awt.Color(255, 255, 255));
        btnPalavras.setText("Escolher palavra");
        btnPalavras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalavrasActionPerformed(evt);
            }
        });

        btnCadastro.setBackground(new java.awt.Color(27, 117, 209));
        btnCadastro.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro.setText("Cadastro");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        btnTroca.setBackground(new java.awt.Color(27, 117, 209));
        btnTroca.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        btnTroca.setForeground(new java.awt.Color(255, 255, 255));
        btnTroca.setText("Trocar conta");
        btnTroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrocaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPalavras)
                            .addComponent(btnJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEstatisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTroca, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnJogar)
                .addGap(18, 18, 18)
                .addComponent(btnPalavras)
                .addGap(18, 18, 18)
                .addComponent(btnEstatisticas)
                .addGap(18, 18, 18)
                .addComponent(btnCadastro)
                .addGap(18, 18, 18)
                .addComponent(btnTroca)
                .addGap(18, 18, 18)
                .addComponent(btnSair)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        formJogo objJogo = new formJogo();
        PartidasDao prtdD = new PartidasDao();

        String palavra = formPalavra.plvr.palavra;
        if (palavra == null) {
            JOptionPane.showMessageDialog(null, "Escolha uma palavra antes de jogar!");
        } else {
            objJogo.setVisible(true);
            this.setVisible(false);
        }

        jd = formCadastro.Jgd;
        if (jd.idUsuario == null) {
            jd = formLogin.usuario;
        }
        Palavras plv = new Palavras();
        plv = formPalavra.plvr;

        LocalDateTime currentTime = LocalDateTime.now();
        prtd.setDataHora(currentTime.toString());
        prtd.setPalavraUtilizada(palavra);

        prtdD.incluir(prtd, jd, plv);

    }//GEN-LAST:event_btnJogarActionPerformed

    private void btnPalavrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalavrasActionPerformed
        formPalavra objPalavra = new formPalavra();
        objPalavra.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnPalavrasActionPerformed

    private void btnEstatisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstatisticasActionPerformed
        formEst fE = new formEst();
        this.setVisible(false);
        fE.setVisible(true);
    }//GEN-LAST:event_btnEstatisticasActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose(); // Fecha o JFrame
        System.exit(0); // Encerra o programa com código de saída 0
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        formCadastro fc = new formCadastro();
        this.setVisible(false);
        fc.setVisible(true);
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnTrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrocaActionPerformed
        formLogin fl = new formLogin();
        
        fl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTrocaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnEstatisticas;
    private javax.swing.JButton btnJogar;
    private javax.swing.JButton btnPalavras;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnTroca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
